# Generated by Django 2.0.6 on 2018-10-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='recipe',
            field=models.TextField(max_length=1000),
        ),
    ]
